# Generated by Django 3.1.5 on 2021-01-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('prize', models.FloatField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
